version: 0.0
os: linux
files:
 - source: /
   destination: /var/www/stocknews
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 30
      runas: root
